
global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'your-email@gmail.com'
  smtp_auth_username: 'your-email@gmail.com'
  smtp_auth_password: 'your-app-password'

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'email-notifications'

receivers:
  - name: 'email-notifications'
    email_configs:
      - to: 'admin@yourcafe.com'
        subject: '🚨 QR Cafe Alert: {{ .GroupLabels.alertname }}'
        body: |
          Alert: {{ .GroupLabels.alertname }}
          
          Summary: {{ range .Alerts }}{{ .Annotations.summary }}{{ end }}
          
          Description: {{ range .Alerts }}{{ .Annotations.description }}{{ end }}
          
          Time: {{ .CommonAnnotations.time }}
          
          Please check the system immediately!

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
