
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qr-cafe-frontend
  namespace: qr-cafe
spec:
  replicas: 2
  selector:
    matchLabels:
      app: qr-cafe-frontend
  template:
    metadata:
      labels:
        app: qr-cafe-frontend
    spec:
      containers:
      - name: frontend
        image: ghcr.io/yourusername/qr-cafe-frontend:latest
        ports:
        - containerPort: 80
        env:
        - name: REACT_APP_API_URL
          value: "http://qr-cafe-backend:3001"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: qr-cafe-frontend
  namespace: qr-cafe
spec:
  selector:
    app: qr-cafe-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
