
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: qr-cafe
type: Opaque
data:
  password: cGFzc3dvcmQxMjM=  # base64 encoded "password123"
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: qr-cafe
type: Opaque
data:
  jwt-secret: eW91ci1zdXBlci1zZWNyZXQtand0LWtleQ==  # base64 encoded "your-super-secret-jwt-key"
